# Maven package Java
# Build your Java project
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage Maven Package and Publish Artifacts
  jobs:
  - job: MavenPackageAndPublishArtifacts

  pool:
    vmImage: $(vmImageName)

  steps:
  - task: Maven@3
    displayName: 'Maven Package'
    inputs:
    mavenPomFile: 'pom.xml'

  - task: CopyFiles@2
    displayName: 'Copy Files to artifact staging directory'
    inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: $(Build.ArtifactStagingDirectory)

  - upload: $(Build.ArtifactStagingDirectory)
    artifact: drop

- Save and run
